#!/bin/bash

echo "----- Test des CHAR -----"
./SCALARCONVERTION a
./SCALARCONVERTION Z
./SCALARCONVERTION %

echo -e "\n----- Test des INT -----"
./SCALARCONVERTION 0
./SCALARCONVERTION 42
./SCALARCONVERTION -42
./SCALARCONVERTION 2147483647   # INT_MAX
./SCALARCONVERTION -2147483648  # INT_MIN

echo -e "\n----- Test des FLOAT -----"
./SCALARCONVERTION 4.2f
./SCALARCONVERTION -4.2f
./SCALARCONVERTION 0.0f
./SCALARCONVERTION nanf
./SCALARCONVERTION inff
./SCALARCONVERTION -inff

echo -e "\n----- Test des DOUBLE -----"
./SCALARCONVERTION 4.2
./SCALARCONVERTION -4.2
./SCALARCONVERTION 0.0
./SCALARCONVERTION nan
./SCALARCONVERTION inf
./SCALARCONVERTION -inf

echo -e "\n----- Test des ERREURS OU LIMITES -----"
./SCALARCONVERTION hello
./SCALARCONVERTION 99999999999999999999999999999
./SCALARCONVERTION ''